// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06tveksLIURb3E48ER4Q_Xcj9nUW4_Dg',
    appId: '1:643314550190:web:2582d1a4780b0c3cd3743f',
    messagingSenderId: '643314550190',
    projectId: 'glucoreminder',
    authDomain: 'glucoreminder.firebaseapp.com',
    storageBucket: 'glucoreminder.firebasestorage.app',
    measurementId: 'G-PR3681QZZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ehuqzeqMSPRvJ439ZMIc8gVIbqWscCg',
    appId: '1:643314550190:android:22ee8df98bc9166ad3743f',
    messagingSenderId: '643314550190',
    projectId: 'glucoreminder',
    storageBucket: 'glucoreminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSKjevhcxCiTyUI8H8d9cxyTdEVefScFg',
    appId: '1:643314550190:ios:cc41b428cf4a332dd3743f',
    messagingSenderId: '643314550190',
    projectId: 'glucoreminder',
    storageBucket: 'glucoreminder.firebasestorage.app',
    iosBundleId: 'com.example.glucoReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSKjevhcxCiTyUI8H8d9cxyTdEVefScFg',
    appId: '1:643314550190:ios:cc41b428cf4a332dd3743f',
    messagingSenderId: '643314550190',
    projectId: 'glucoreminder',
    storageBucket: 'glucoreminder.firebasestorage.app',
    iosBundleId: 'com.example.glucoReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD06tveksLIURb3E48ER4Q_Xcj9nUW4_Dg',
    appId: '1:643314550190:web:3a78e90d5bfdf296d3743f',
    messagingSenderId: '643314550190',
    projectId: 'glucoreminder',
    authDomain: 'glucoreminder.firebaseapp.com',
    storageBucket: 'glucoreminder.firebasestorage.app',
    measurementId: 'G-3YCS7M1QR8',
  );
}
